### ISSUE TITLE
Ftp command FEAT return code invalid?

### ISSUE THREAD

**Issue by r3dqu33n** [VoDACode/VoDA.FtpServer#2]
Hello, 

I'm trying to implement a minimal FTP Server and doing some tests with WinSCP.
i've found that the response code to a FEAT command is a 221 closing the underlying connection; but being the corrrect response code 211 according to the RFC https://datatracker.ietf.org/doc/html/rfc2389#section-3.2.

Thank you.

**Comment by VoDACode** [comment]
Hello. 
Bug fixed. Update the package to version [1.3.6](https://www.nuget.org/packages/VoDA.FtpServer/1.3.6).
Thanks for the information.
