### ISSUE TITLE
PORT command may calculate negative port numbers

### ISSUE THREAD

**Issue by harenbrs** [VoDACode/VoDA.FtpServer#5]
Port numbers should be UInt16, but in `VoDA.FtpServer/Commands/PortCommand.cs` the port number is calculated using `BitConverter.ToInt16(port, 0)`. This leads to exceptions and dropped connections (in my experience especially in active mode).

**Comment by VoDACode** [comment]
Hello! Thank you for your response. This issue has been fixed in version [1.3.9](https://www.nuget.org/packages/VoDA.FtpServer/1.3.9).
